.deploy_rust_bin: &deploy_rust_bin
  stage: deploy
  tags:
    - ansible
  script:
    - ansible-playbook -i .ansible/hosts .ansible/$PLAYBOOK
  when: manual

deploy_invoicer:
  <<: *deploy_rust_bin
  dependencies:
    - build_invoicer 
  variables:
    PLAYBOOK: deploy_invoicer.yml


deploy_rating_bot:
  <<: *deploy_rust_bin
  dependencies:
    - build_rating_bot
  variables:
    PLAYBOOK: deploy_rating_bot.yml

