version: "3.8"

services:
  fuente-invoicer:
    image: rust:1.84-bookworm
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    environment:
      - LND_ADDRESS=${LND_ADDRESS}
      - LND_MACAROON=${LND_MACAROON}
      - FUENTE_PRIV_KEY=${FUENTE_PRIV_KEY}
      - UT_API_KEY=${UT_API_KEY}
      - UT_APP_ID=${UT_APP_ID}
      - UT_CALLBACK_DOMAIN=${UT_CALLBACK_DOMAIN}
    networks:
      - invoicer
    command: ./fuente-invoicer

networks:
  invoicer:
    name: invoicer
    driver: bridge
