version: "3.8"

services:
  fuente-invoicer:
    build:
      context: .
    volumes:
      - /opt/fuente/invoicer:/app
    working_dir: /app
    restart: unless-stopped
    environment:
      - LND_ADDRESS=${LND_ADDRESS}
      - LND_MACAROON=${LND_MACAROON}
      - FUENTE_PRIV_KEY=${FUENTE_PRIV_KEY}
      - UT_API_KEY=${UT_API_KEY}
      - UT_APP_ID=${UT_APP_ID}
      - UT_CALLBACK_DOMAIN=${UT_CALLBACK_DOMAIN}
    networks:
      - illuminodes

networks:
  illuminodes:
    name: illuminodes
