version: "3.8"

services:
  fuente-ratings:
    image: rust:1.84-bookworm
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped
    environment:
      - FUENTE_PRIV_KEY=${FUENTE_PRIV_KEY}
    networks:
      - ratings
    command: ./fuente-ratings

networks:
  ratings:
    driver: bridge
