version: "3.8"

services:
  fuente-ratings:
    build:
      context: .
    volumes:
      - /opt/fuente/rating-bot:/app
    working_dir: /app
    restart: unless-stopped
    environment:
      - FUENTE_PRIV_KEY=${FUENTE_PRIV_KEY}
    networks:
      - ratings

networks:
  ratings:
    driver: bridge
